### ISSUE TITLE
Remove env-variable manipulations

### ISSUE THREAD

**Issue by joakim-hove** [Statoil/ert#163]
Here: https://github.com/Statoil/ert/blob/master/bin/ert.in#L8 the environment of the running ERT process is manipulated runtime. 

This seems convenient at first - but it comes back to haunt you; at least the `PYTHONPATH` come in conflict with RMS and should be removed. Might induce other breakage  ... :-(

**Comment by lars-petter-hauge** [comment]
So I've removed the editing of the env variables (need to update some tests though) in the referred PR

The GUI images etc should perhaps be relocated to within the site-packages, as is common with other python libraries. Using setup.py as part of the make process would do this for us, so I'll leave things as they are now.
