### ISSUE TITLE
Advanced option

### ISSUE THREAD

**Issue by geirev** [Statoil/ert#223]
I see you have removed "View/Advanced Options" from the main ERT menu.

It is not clear to me how you now can select a loaded analysis module for Iterated Ensemble Smoother which previously appeared on the Simulation mode button when Advanced options were set.

**Comment by markusdregi** [comment]
The idea is that advanced mode is the only mode... If there’s functionality that disappeared in the process, we’ll look into that!

**Comment by geirev** [comment]
The Iterated Ensemble Smoother option/panel is only active when "Advanced options" is selected AND an iterated smoother is loaded, e.g., rml.    Further, when selecting the Iterated Ensemble Smoother the Edit variables panel should also be available.

**Comment by markusdregi** [comment]
@geirev This should be resolved now...
